export interface Product {
  id: string;
  name: string;
  category: string;
  price: number;
  image: string;
  description: string;
  sizes: string[];
  rating: number;
  reviews: number;
  inStock: boolean;
}

const productImg = (filename: string) => `/productimg/${encodeURIComponent(filename)}`;
const defaultProductImage = productImg('logo.jpeg');

export const products: Product[] = [
  // Full Set Bundle (5 colors)
  {
    id: '1',
    name: 'Full Set - Hoodie & Sweatpants (Black)',
    category: 'bundle',
    price: 4000,
    image: productImg('ADIN KENYA est 2023.jpeg'),
    description: 'Complete black hoodie and matching sweatpants set.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviews: 0,
    inStock: true,
  },
  {
    id: '2',
    name: 'Full Set - Hoodie & Sweatpants (White)',
    category: 'bundle',
    price: 4000,
    image: defaultProductImage,
    description: 'Complete white hoodie and matching sweatpants set.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviews: 0,
    inStock: true,
  },
  {
    id: '3',
    name: 'Full Set - Hoodie & Sweatpants (Brown)',
    category: 'bundle',
    price: 4000,
    image: productImg('brownmatching sweatpants2.jpeg'),
    description: 'Complete brown hoodie and matching sweatpants set.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviews: 0,
    inStock: true,
  },
  {
    id: '4',
    name: 'Full Set - Hoodie & Sweatpants (Navy Blue)',
    category: 'bundle',
    price: 4000,
    image: productImg('navy blue set.jpeg'),
    description: 'Complete navy blue hoodie and matching sweatpants set.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviews: 0,
    inStock: true,
  },
  {
    id: '5',
    name: 'Full Set - Hoodie & Sweatpants (Charcoal)',
    category: 'bundle',
    price: 4000,
    image: defaultProductImage,
    description: 'Complete charcoal hoodie and matching sweatpants set.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviews: 0,
    inStock: true,
  },

  // Hoodies (5 colors)
  {
    id: '6',
    name: 'Hoodie (Black)',
    category: 'hoodies',
    price: 2700,
    image: productImg('Walk With Confidence.JPG'),
    description: 'Premium black hoodie.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },
  {
    id: '7',
    name: 'Hoodie (White)',
    category: 'hoodies',
    price: 2700,
    image: defaultProductImage,
    description: 'Premium white hoodie.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },
  {
    id: '8',
    name: 'Hoodie (Brown)',
    category: 'hoodies',
    price: 2700,
    image: productImg('brownmatching sweatpants2.jpeg'),
    description: 'Premium brown hoodie.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },
  {
    id: '9',
    name: 'Hoodie (Navy Blue)',
    category: 'hoodies',
    price: 2700,
    image: productImg('navy blue set.jpeg'),
    description: 'Premium navy blue hoodie.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },
  {
    id: '10',
    name: 'Hoodie (Charcoal)',
    category: 'hoodies',
    price: 2700,
    image: productImg('grayHoodie.jpeg'),
    description: 'Premium charcoal hoodie.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },

  // Sweatpants (5 colors)
  {
    id: '11',
    name: 'Sweatpants (Black)',
    category: 'sweatpants',
    price: 1700,
    image: defaultProductImage,
    description: 'Premium black sweatpants.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },
  {
    id: '12',
    name: 'Sweatpants (White)',
    category: 'sweatpants',
    price: 1700,
    image: defaultProductImage,
    description: 'Premium white sweatpants.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },
  {
    id: '13',
    name: 'Sweatpants (Brown)',
    category: 'sweatpants',
    price: 1700,
    image: productImg('matching sweatpants.jpeg'),
    description: 'Premium brown sweatpants.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },
  {
    id: '14',
    name: 'Sweatpants (Navy Blue)',
    category: 'sweatpants',
    price: 1700,
    image: defaultProductImage,
    description: 'Premium navy blue sweatpants.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },
  {
    id: '15',
    name: 'Sweatpants (Charcoal)',
    category: 'sweatpants',
    price: 1700,
    image: defaultProductImage,
    description: 'Premium charcoal sweatpants.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },

  // Varsity Jackets (5 colors)
  {
    id: '16',
    name: 'Varsity Jacket (Black)',
    category: 'jackets',
    price: 2800,
    image: productImg('Studio portrait.JPG'),
    description: 'Classic black varsity jacket.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviews: 0,
    inStock: true,
  },
  {
    id: '17',
    name: 'Varsity Jacket (White)',
    category: 'jackets',
    price: 2800,
    image: productImg('whitevarsityjacket.jpg'),
    description: 'Classic white varsity jacket.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviews: 0,
    inStock: true,
  },
  {
    id: '18',
    name: 'Varsity Jacket (Brown)',
    category: 'jackets',
    price: 2800,
    image: defaultProductImage,
    description: 'Classic brown varsity jacket.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviews: 0,
    inStock: true,
  },
  {
    id: '19',
    name: 'Varsity Jacket (Navy Blue)',
    category: 'jackets',
    price: 2800,
    image: productImg('bluevarsityjacket.jpg'),
    description: 'Classic navy blue varsity jacket.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviews: 0,
    inStock: true,
  },
  {
    id: '20',
    name: 'Varsity Jacket (Charcoal)',
    category: 'jackets',
    price: 2800,
    image: defaultProductImage,
    description: 'Classic charcoal varsity jacket.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviews: 0,
    inStock: true,
  },

  // Sweat Shorts (5 colors)
  {
    id: '21',
    name: 'Sweat Shorts (Black)',
    category: 'shorts',
    price: 1300,
    image: defaultProductImage,
    description: 'Black sweat shorts.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 0,
    inStock: true,
  },
  {
    id: '22',
    name: 'Sweat Shorts (White)',
    category: 'shorts',
    price: 1300,
    image: defaultProductImage,
    description: 'White sweat shorts.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 0,
    inStock: true,
  },
  {
    id: '23',
    name: 'Sweat Shorts (Brown)',
    category: 'shorts',
    price: 1300,
    image: defaultProductImage,
    description: 'Brown sweat shorts.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 0,
    inStock: true,
  },
  {
    id: '24',
    name: 'Sweat Shorts (Navy Blue)',
    category: 'shorts',
    price: 1300,
    image: defaultProductImage,
    description: 'Navy blue sweat shorts.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 0,
    inStock: true,
  },
  {
    id: '25',
    name: 'Sweat Shorts (Charcoal)',
    category: 'shorts',
    price: 1300,
    image: defaultProductImage,
    description: 'Charcoal sweat shorts.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 0,
    inStock: true,
  },

  // Sweatshirts (5 colors)
  {
    id: '26',
    name: 'Sweatshirt (Black)',
    category: 'sweatshirts',
    price: 2200,
    image: defaultProductImage,
    description: 'Black crew sweatshirt.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },
  {
    id: '27',
    name: 'Sweatshirt (White)',
    category: 'sweatshirts',
    price: 2200,
    image: defaultProductImage,
    description: 'White crew sweatshirt.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },
  {
    id: '28',
    name: 'Sweatshirt (Brown)',
    category: 'sweatshirts',
    price: 2200,
    image: defaultProductImage,
    description: 'Brown crew sweatshirt.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },
  {
    id: '29',
    name: 'Sweatshirt (Navy Blue)',
    category: 'sweatshirts',
    price: 2200,
    image: defaultProductImage,
    description: 'Navy blue crew sweatshirt.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },
  {
    id: '30',
    name: 'Sweatshirt (Charcoal)',
    category: 'sweatshirts',
    price: 2200,
    image: defaultProductImage,
    description: 'Charcoal crew sweatshirt.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },

  // Heavy Duty T-Shirts (5 colors)
  {
    id: '31',
    name: 'Heavy Duty T-Shirt (Black)',
    category: 'tshirts',
    price: 1200,
    image: productImg('blacktshirt.jpg'),
    description: 'Heavy duty black tee.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 0,
    inStock: true,
  },
  {
    id: '32',
    name: 'Heavy Duty T-Shirt (White)',
    category: 'tshirts',
    price: 1200,
    image: productImg('whitepoloshirt.jpg'),
    description: 'Heavy duty white tee.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 0,
    inStock: true,
  },
  {
    id: '33',
    name: 'Heavy Duty T-Shirt (Brown)',
    category: 'tshirts',
    price: 1200,
    image: defaultProductImage,
    description: 'Heavy duty brown tee.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 0,
    inStock: true,
  },
  {
    id: '34',
    name: 'Heavy Duty T-Shirt (Navy Blue)',
    category: 'tshirts',
    price: 1200,
    image: defaultProductImage,
    description: 'Heavy duty navy blue tee.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 0,
    inStock: true,
  },
  {
    id: '35',
    name: 'Heavy Duty T-Shirt (Charcoal)',
    category: 'tshirts',
    price: 1200,
    image: defaultProductImage,
    description: 'Heavy duty charcoal tee.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 0,
    inStock: true,
  },

  // Trucker Hats (5 colors)
  {
    id: '36',
    name: 'Trucker Hat (Black)',
    category: 'caps',
    price: 800,
    image: productImg('blackandredcap.jpeg'),
    description: 'Black trucker hat.',
    sizes: ['One Size'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },
  {
    id: '37',
    name: 'Trucker Hat (White)',
    category: 'caps',
    price: 800,
    image: defaultProductImage,
    description: 'White trucker hat.',
    sizes: ['One Size'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },
  {
    id: '38',
    name: 'Trucker Hat (Brown)',
    category: 'caps',
    price: 800,
    image: defaultProductImage,
    description: 'Brown trucker hat.',
    sizes: ['One Size'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },
  {
    id: '39',
    name: 'Trucker Hat (Navy Blue)',
    category: 'caps',
    price: 800,
    image: defaultProductImage,
    description: 'Navy blue trucker hat.',
    sizes: ['One Size'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },
  {
    id: '40',
    name: 'Trucker Hat (Charcoal)',
    category: 'caps',
    price: 800,
    image: defaultProductImage,
    description: 'Charcoal trucker hat.',
    sizes: ['One Size'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },

  // Extra assets: Red + Yellow variants
  {
    id: '41',
    name: 'Varsity Jacket (Red)',
    category: 'jackets',
    price: 2800,
    image: productImg('modelredvarsityjacket3.jpg'),
    description: 'Classic red varsity jacket.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviews: 0,
    inStock: true,
  },
  {
    id: '42',
    name: 'Trucker Hat (Red)',
    category: 'caps',
    price: 800,
    image: productImg('redcap.jpeg'),
    description: 'Red trucker hat.',
    sizes: ['One Size'],
    rating: 4.8,
    reviews: 0,
    inStock: true,
  },
  {
    id: '43',
    name: 'Heavy Duty T-Shirt (Yellow)',
    category: 'tshirts',
    price: 1200,
    image: productImg('yellowpoloshirt.jpg'),
    description: 'Heavy duty yellow tee.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 0,
    inStock: true,
  },
];

export const categories = [
  { id: 'bundle', name: 'Bundle Deals', count: 5 },
  { id: 'hoodies', name: 'Hoodies', count: 5 },
  { id: 'sweatpants', name: 'Sweatpants', count: 5 },
  { id: 'jackets', name: 'Varsity Jackets', count: 6 },
  { id: 'shorts', name: 'Sweat Shorts', count: 5 },
  { id: 'sweatshirts', name: 'Sweatshirts', count: 5 },
  { id: 'tshirts', name: 'T-Shirts', count: 6 },
  { id: 'caps', name: 'Trucker Hats', count: 6 },
];

export const sizes = ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'One Size'];
export const priceRanges = [
  { min: 0, max: 1000, label: 'Under KSh 1,000' },
  { min: 1000, max: 2000, label: 'KSh 1,000 - KSh 2,000' },
  { min: 2000, max: 3000, label: 'KSh 2,000 - KSh 3,000' },
  { min: 3000, max: 5000, label: 'KSh 3,000+' },
];
