export interface Product {
  id: string;
  name: string;
  category: string;
  price: number;
  image: string;
  description: string;
  sizes: string[];
  rating: number;
  reviews: number;
  inStock: boolean;
}

export const products: Product[] = [
  // Sweatpants
  {
    id: '1',
    name: 'Premium Comfort Sweatpants',
    category: 'sweatpants',
    price: 89,
    image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=500&h=500&fit=crop',
    description: 'Ultra-soft, premium cotton sweatpants designed for maximum comfort and style.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 234,
    inStock: true,
  },
  {
    id: '2',
    name: 'Black Track Pants',
    category: 'sweatpants',
    price: 79,
    image: 'https://images.unsplash.com/photo-1506629082632-07fef77e3895?w=500&h=500&fit=crop',
    description: 'Classic black track pants with a modern silhouette.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    rating: 4.6,
    reviews: 156,
    inStock: true,
  },
  {
    id: '3',
    name: 'Tapered Joggers',
    category: 'sweatpants',
    price: 85,
    image: 'https://images.unsplash.com/photo-1607479591341-f5ef290b9fb0?w=500&h=500&fit=crop',
    description: 'Stylish tapered joggers perfect for both gym and casual wear.',
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviews: 198,
    inStock: true,
  },
  {
    id: '4',
    name: 'Charcoal Sweatpants',
    category: 'sweatpants',
    price: 89,
    image: 'https://images.unsplash.com/photo-1523439732248-4b5a7b96c5d4?w=500&h=500&fit=crop',
    description: 'Versatile charcoal sweatpants made from premium fabric blend.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviews: 287,
    inStock: true,
  },
  {
    id: '5',
    name: 'Navy Sports Pants',
    category: 'sweatpants',
    price: 75,
    image: 'https://images.unsplash.com/photo-1548690596-f1e8a5dff69f?w=500&h=500&fit=crop',
    description: 'Lightweight navy sports pants ideal for active wear.',
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.5,
    reviews: 142,
    inStock: true,
  },
  {
    id: '6',
    name: 'Winter Fleece Pants',
    category: 'sweatpants',
    price: 95,
    image: 'https://images.unsplash.com/photo-1505233604001-2e099016d81f?w=500&h=500&fit=crop',
    description: 'Warm and cozy fleece-lined sweatpants for winter comfort.',
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 215,
    inStock: true,
  },

  // T-Shirts
  {
    id: '7',
    name: 'Classic Black Tee',
    category: 'tshirts',
    price: 34,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
    description: 'Essential black t-shirt made from premium cotton.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 412,
    inStock: true,
  },
  {
    id: '8',
    name: 'White Minimalist Tee',
    category: 'tshirts',
    price: 34,
    image: 'https://images.unsplash.com/photo-1581684804309-e82b1ce6d4dc?w=500&h=500&fit=crop',
    description: 'Clean white tee perfect for any outfit.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 523,
    inStock: true,
  },
  {
    id: '9',
    name: 'Charcoal Gray Basic',
    category: 'tshirts',
    price: 32,
    image: 'https://images.unsplash.com/photo-1505887314467-1eb4a3a937ca?w=500&h=500&fit=crop',
    description: 'Versatile charcoal gray tee for everyday wear.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.6,
    reviews: 287,
    inStock: true,
  },
  {
    id: '10',
    name: 'Navy Crew Neck',
    category: 'tshirts',
    price: 36,
    image: 'https://images.unsplash.com/photo-1618686244015-58624e922b97?w=500&h=500&fit=crop',
    description: 'Classic navy crew neck tee for timeless style.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviews: 198,
    inStock: true,
  },
  {
    id: '11',
    name: 'Heather Brown Tee',
    category: 'tshirts',
    price: 38,
    image: 'https://images.unsplash.com/photo-1595627712322-ca51fb337314?w=500&h=500&fit=crop',
    description: 'Warm heather brown tee with a relaxed fit.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.5,
    reviews: 165,
    inStock: true,
  },
  {
    id: '12',
    name: 'Premium Cotton Tee',
    category: 'tshirts',
    price: 40,
    image: 'https://images.unsplash.com/photo-1503341512671-18f509602a97?w=500&h=500&fit=crop',
    description: 'Ultra-premium 100% cotton tee with exceptional durability.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviews: 389,
    inStock: true,
  },

  // Jackets
  {
    id: '13',
    name: 'Classic Leather Jacket',
    category: 'jackets',
    price: 249,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=500&h=500&fit=crop',
    description: 'Timeless leather jacket for ultimate style and protection.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    rating: 4.9,
    reviews: 178,
    inStock: true,
  },
  {
    id: '14',
    name: 'Black Bomber Jacket',
    category: 'jackets',
    price: 199,
    image: 'https://images.unsplash.com/photo-1591047990976-ff5b2835b40c?w=500&h=500&fit=crop',
    description: 'Modern bomber jacket with premium finish.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 234,
    inStock: true,
  },
  {
    id: '15',
    name: 'Navy Windbreaker',
    category: 'jackets',
    price: 159,
    image: 'https://images.unsplash.com/photo-1494820282797-2b71b471f047?w=500&h=500&fit=crop',
    description: 'Lightweight and weather-resistant windbreaker.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.6,
    reviews: 156,
    inStock: true,
  },
  {
    id: '16',
    name: 'Charcoal Denim Jacket',
    category: 'jackets',
    price: 169,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=500&h=500&fit=crop',
    description: 'Classic charcoal denim jacket with a modern cut.',
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.8,
    reviews: 212,
    inStock: true,
  },
  {
    id: '17',
    name: 'Brown Suede Jacket',
    category: 'jackets',
    price: 279,
    image: 'https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=500&h=500&fit=crop',
    description: 'Luxurious brown suede jacket for refined taste.',
    sizes: ['M', 'L', 'XL'],
    rating: 4.9,
    reviews: 134,
    inStock: true,
  },
  {
    id: '18',
    name: 'Puffer Winter Jacket',
    category: 'jackets',
    price: 229,
    image: 'https://images.unsplash.com/photo-1539533057440-7814a9d826d7?w=500&h=500&fit=crop',
    description: 'Insulated puffer jacket for extreme cold weather.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviews: 298,
    inStock: true,
  },

  // Caps
  {
    id: '19',
    name: 'Black Snapback Cap',
    category: 'caps',
    price: 29,
    image: 'https://images.unsplash.com/photo-1551316679-9c6ae9dec224?w=500&h=500&fit=crop',
    description: 'Classic black snapback cap with adjustable fit.',
    sizes: ['One Size'],
    rating: 4.6,
    reviews: 289,
    inStock: true,
  },
  {
    id: '20',
    name: 'Navy Baseball Cap',
    category: 'caps',
    price: 32,
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500&h=500&fit=crop',
    description: 'Premium navy baseball cap with curved bill.',
    sizes: ['One Size'],
    rating: 4.7,
    reviews: 234,
    inStock: true,
  },
  {
    id: '21',
    name: 'Brown Leather Cap',
    category: 'caps',
    price: 45,
    image: 'https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=500&h=500&fit=crop',
    description: 'Sophisticated brown leather cap for timeless style.',
    sizes: ['One Size'],
    rating: 4.8,
    reviews: 156,
    inStock: true,
  },
  {
    id: '22',
    name: 'White Trucker Hat',
    category: 'caps',
    price: 35,
    image: 'https://images.unsplash.com/photo-1572365992253-3cb3e56dd362?w=500&h=500&fit=crop',
    description: 'Classic white trucker hat with mesh back.',
    sizes: ['One Size'],
    rating: 4.5,
    reviews: 178,
    inStock: true,
  },
  {
    id: '23',
    name: 'Charcoal Beanie',
    category: 'caps',
    price: 25,
    image: 'https://images.unsplash.com/photo-1515992332449-5efa3a5fbc87?w=500&h=500&fit=crop',
    description: 'Cozy charcoal beanie for winter wear.',
    sizes: ['One Size'],
    rating: 4.7,
    reviews: 267,
    inStock: true,
  },
  {
    id: '24',
    name: 'Black Dad Hat',
    category: 'caps',
    price: 28,
    image: 'https://images.unsplash.com/photo-1598033129519-238cabe66d16?w=500&h=500&fit=crop',
    description: 'Vintage-inspired black dad hat with curved brim.',
    sizes: ['One Size'],
    rating: 4.6,
    reviews: 145,
    inStock: true,
  },
];

export const categories = [
  { id: 'sweatpants', name: 'Sweatpants', count: 6 },
  { id: 'tshirts', name: 'T-Shirts', count: 6 },
  { id: 'jackets', name: 'Jackets', count: 6 },
  { id: 'caps', name: 'Caps', count: 6 },
];

export const sizes = ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'One Size'];
export const priceRanges = [
  { min: 0, max: 50, label: 'Under KSh 50' },
  { min: 50, max: 100, label: 'KSh 50 - KSh 100' },
  { min: 100, max: 200, label: 'KSh 100 - KSh 200' },
  { min: 200, max: 500, label: 'KSh 200+' },
];
